### ISSUE TITLE
cpp API is available

### ISSUE THREAD

**Issue by FluorineDog** [klx3300/2017aut-quest2#5]
https://github.com/FluorineDog/2017aut-quest2/tree/cpp
but i don't know how to send the pull request to a new branch.
maybe you need to do it manually, at least create a empty branch for me.
Terrible!

**Comment by klx3300** [comment]
you can post a comment with the link of cpp version API in our forum.
but cpp version will not (and never) be supported *OFFICIALLY*.
ANY FURTHER ISSUES ABOUT CPP APIS WILL BE CLOSED WITHOUT ANY COMMENT.
